export const GET_APPLICATIONS_REQUEST = "GET_APPLICATIONS_REQUEST";
export const GET_APPLICATIONS_SUCCESS = "GET_APPLICATIONS_SUCCESS";
export const GET_APPLICATIONS_FAILURE = "GET_APPLICATIONS_FAILURE";

export const ADD_APPLICATION_REQUEST = "ADD_APPLICATION_REQUEST";
export const ADD_APPLICATION_SUCCESS = "ADD_APPLICATION_SUCCESS";
export const ADD_APPLICATION_FAILURE = "ADD_APPLICATION_FAILURE";

export const GET_OTHER_DEPARTMENTS_REQUEST = "GET_OTHER_DEPARTMENTS_REQUEST";
export const GET_OTHER_DEPARTMENTS_SUCCESS = "GET_OTHER_DEPARTMENTS_SUCCESS";
export const GET_OTHER_DEPARTMENTS_FAILURE = "GET_OTHER_DEPARTMENTS_FAILURE";

export const GET_DEPARTMENT_USERS_REQUEST = "GET_DEPARTMENT_USERS_REQUEST";
export const GET_DEPARTMENT_USERS_SUCCESS = "GET_DEPARTMENT_USERS_SUCCESS";
export const GET_DEPARTMENT_USERS_FAILURE = "GET_DEPARTMENT_USERS_FAILURE";

export const UPDATE_APPLICATION_STATUS_REQUEST =
  "UPDATE_APPLICATION_STATUS_REQUEST";
export const UPDATE_APPLICATION_STATUS_SUCCESS =
  "UPDATE_APPLICATION_STATUS_SUCCESS";
export const UPDATE_APPLICATION_STATUS_FAILURE =
  "UPDATE_APPLICATION_STATUS_FAILURE";
